### PR TITLE
Add spike time test for Arbor and NEURON

### PR DESCRIPTION
**Pull request by halfflat**
Partially satisfies #14. CoreNEURON implementation is not yet there.

* Extend comparex to allow interpolation of 1-d variables across different dimensions.
* Remove `run` from gitignore: `run` is the name of the runner in each validation test. (This will become less of an issue once out-of-tree runs are straightforward — see PR #27.)
* Add new validation test: rc-exp2syn-spike. Computes time to first spike for a number of cells (101 in default parameter set). Cells (index > 0) are connected to the first cell with a quasirandom delay, and the error is computed as the maximum over the cells.
* Fix bug in `run-validation.sh` that effectively prevented multiple models being requested at the command line.

### CODE REVIEW

**Review by bcumming — APPROVED** [review]
Looks good.

Just one comment: what is your policy with naming Python scripts with `.py` file endings? In some cases you do, and others you don't.

I would strongly want to see `.py` endings, to describe the file.

**Comment by halfflat** [comment]
For tools which are called from other scripts, where the fact that they are implemented in Python is just an implementation detail, I prefer to leave off any extension. If I came by tomorrow and redid them in C++, I shouldn't have to change any scripts that use them.

For the bits and pieces within a validation test directory, the name of the Python program that does the work is called in exactly one place, and there it doesn't really matter from a maintenance point of view whether it has a .py suffix or not. It might as well, as I know you generally prefer them to be so marked.

**Comment by bcumming** [comment]
I really think that it is good practice to use file endings to indicate the type of the file. The fact that something is a python script is an implementation detail that is usually indicated with an extension.
When looking at the contents of a path, without an extension it is not possible to say what that file is.

**Comment by halfflat** [comment]
But it doesn't matter what it is ... I don't see how having the name of an executable program indicate the language it is written in is of any utility.

Looking at the content will immediately reveal it is in Python.

**Pull request merged**
